smartcoop/smart-cfa

- src/Smart.FA.Catalog.Application/UseCases/Commands/EditProfileCommand.cs
- src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainerProfileQuery.cs
- src/Smart.FA.Catalog.Core/Domain/Trainer/Enumerations/SocialNetwork.cs
- src/Smart.FA.Catalog.Core/Domain/Trainer/PersonalSocialNetwork.cs
- src/Smart.FA.Catalog.Core/Domain/Trainer/Trainer.cs
- src/Smart.FA.Catalog.Infrastructure/Migrations/20220307092308_Add_Personal_Social_Network_To_Trainer.Designer.cs
- src/Smart.FA.Catalog.Infrastructure/Migrations/20220307092308_Add_Personal_Social_Network_To_Trainer.cs
- src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainerConfiguration.cs
- src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainerPersonalNetworkConfiguration.cs
- src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
- src/Smart.FA.Catalog.Web/Pages/Admin/SideMenuItems.cs
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
- src/Smart.FA.Catalog.Web/Program.cs
- src/Smart.FA.Catalog.Web/Resources/Pages/Admin/Trainings/List/ListModel.Designer.cs
- src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs
- src/Smart.FA.Catalog.Web/Web.csproj
The PR brings the possibility to edit a trainer profile.
> Add the edition of a trainer profile

- Jenkinsfile
- docker-compose.yml
- jenkins-build.sh
- jenkins-deploy.sh
- jenkins-run.sh
- src/Smart.FA.Catalog.Web/appsettings.json
Smart-cfa :
When the developer create one branch xxx.
The build deploy on xxx.cfa.smartcoop.dev.
https://smartjira.atlassian.net/browse/CFA-198
> Change docker build to docker-compose build for jenkins-build.sh

- Smart.FA.Catalog.IntegrationTests/Repositories/TrainerRepository_Tests.cs
- Smart.FA.Catalog.IntegrationTests/Repositories/TrainingRepository_Tests.cs
- Smart.FA.Catalog.IntegrationTests/Smart.FA.Catalog.IntegrationTests.csproj
- Smart.FA.Catalog.IntegrationTests/TrainingContext/Trainer_Tests.cs
- Smart.FA.Catalog.IntegrationTests/TrainingContext/Training_Tests.cs
- Smart.FA.Catalog.Tests.Common/TrainerFactory.cs
- Smart.FA.Catalog.Tests.Common/TrainingFactory.cs
- Smart.FA.Catalog.Tests.Common/UserFactory.cs
- Smart.FA.Catalog.UnitTests/Smart.FA.Catalog.UnitTests.csproj
- Smart.FA.Catalog.UnitTests/Trainer_Tests.cs
- Smart.FA.Catalog.UnitTests/Training_Tests.cs
- Make factory test methods static
- Replace Moq by NSubstitute
> Rector factory method and mocking of test project

- src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.css
- src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
- src/Smart.FA.Catalog.Web/Pages/Shared/_Layout.cshtml
https://smartjira.atlassian.net/browse/CFA-234
The look of the profile page with this commit is the following:
> Add the HTML to display a trainer profile's picture

- src/Smart.FA.Catalog.Application/Application.csproj
- src/Smart.FA.Catalog.Application/Extensions/ServiceCollectionExtensions.cs
- src/Smart.FA.Catalog.Application/Interceptors/LoggingPipelineBehavior.cs
- src/Smart.FA.Catalog.Core/Exceptions/Error.cs
- src/Smart.FA.Catalog.Core/LogEvents/GeneralLogEvents.cs
- src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
Generic logging behaviour for query and command handlers
> Add behaviour pipeline for logging in handlers

- Web.Dockerfile
Simply renaming dockerfile  names to reflect the changes in the name of the csproj.
> Change dockerfile to reflect csproj name

- src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/Smart.FA.Catalog.Web/Pages/Admin/SideMenuItems.cs
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
Adds translations I forgot to publish.
> Add more translations

- src/Smart.FA.Catalog.Core/Domain/Training/Enumerations/TrainingStatus.cs
- src/Smart.FA.Catalog.Core/SeedWork/Enumeration.cs
- src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
- src/Smart.FA.Catalog.Web/Pages/_ViewImports.cshtml
- src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
This commit updates the design but also fixes the checking of topics's checkboxes when editing a training.
The rendered page would have no checkbox checked.
> Update creation an edition pages accordingly to the latest figma update

- src/Smart.FA.Catalog.Core/Domain/Validators/CustomValidators.cs
- src/Smart.FA.Catalog.Core/Domain/Validators/TrainingDetailValidation.cs
- src/Smart.FA.Catalog.Core/Domain/Validators/TrainingValidator.cs
- src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
- src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs
Improve a bit the readability of those validators.
> Refactor training creation/deletion 

- src/Smart.FA.Catalog.Core/Domain/ValueObjects/Name.cs
- src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/Smart.FA.Catalog.Web/Pages/Admin/Index.cshtml
- src/Smart.FA.Catalog.Web/Pages/Admin/Index.cshtml.cs
- src/Smart.FA.Catalog.Web/Pages/Index.cshtml
- src/Smart.FA.Catalog.Web/Pages/Index.cshtml.cs
- src/Smart.FA.Catalog.Web/Pages/Index.cshtml.css
- src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
- src/Smart.FA.Catalog.Web/Pages/Shared/_Layout.cshtml
This comment adds the personal homepage and makes fancier de website homepage.
> Add the hompage of user's personal space

- src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainerProfileQuery.cs
- src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
- src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/AdminTrainingCardViewComponent.cs
- src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
- src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
- src/Smart.FA.Catalog.Web/Pages/Shared/_Layout.cshtml
- src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs
The compiler raises "false positive" warning about nullable types.
This commit fixes that.
> Correct a bunch of warnings about nullable type references

- Smart.FA.Catalog.IntegrationTests/Base/ConnectionSetup.cs
- Smart.FA.Catalog.IntegrationTests/Base/IntegrationTestBase.cs
- Smart.FA.Catalog.IntegrationTests/Base/TestSetup.cs
- Smart.FA.Catalog.IntegrationTests/Repositories/TrainerRepository_Tests.cs
- Smart.FA.Catalog.IntegrationTests/Repositories/TrainingRepository_Tests.cs
- Smart.FA.Catalog.IntegrationTests/Smart.FA.Catalog.IntegrationTests.csproj
- Smart.FA.Catalog.IntegrationTests/TrainingContext/Trainer_Tests.cs
- Smart.FA.Catalog.IntegrationTests/TrainingContext/Training_Tests.cs
- Smart.FA.Catalog.IntegrationTests/TrainingContext/User_Tests.cs
- Smart.FA.Catalog.IntegrationTests/appsettings.json
- src/Smart.FA.Catalog.Infrastructure/DesignTimeContextFactory.cs
- src/Smart.FA.Catalog.Infrastructure/Extensions/ServiceCollectionExtensions.cs
- src/Smart.FA.Catalog.Infrastructure/Options/DALOptions.cs
- src/Smart.FA.Catalog.Infrastructure/Options/EFCore.cs
- src/Smart.FA.Catalog.Infrastructure/Persistence/CatalogContext.cs
- src/Smart.FA.Catalog.Infrastructure/Smart.FA.Catalog.Infrastructure.csproj
- src/Smart.FA.Catalog.Web/Program.cs
- src/Smart.FA.Catalog.Web/appsettings.Development.json
- src/Smart.FA.Catalog.Web/appsettings.Staging.json
- src/Smart.FA.Catalog.Web/appsettings.json
I introduce some small refactoring. 
Since they are very small, instead of spamming you with 3 different PR's, I have madeonly  one PR with some small commits.
The PR includes:
1. Replace hard dependencies in the constructor of the catalog context with an injected option pattern
2. Renaming of the method injecting a catalog context in the integration tests
> Catalog Context refactoring

- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Dto/TrainingDetailDto.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/TrainingDetail.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Validators/TrainingDetailValidation.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Validators/TrainingDetailValidator.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Validators/TrainingValidator.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/SeedWork/Guard.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220405150746_Add_PracticalModalities_To_TrainingDetail.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220405150746_Add_PracticalModalities_To_TrainingDetail.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220407160621_Change_Precision_Training_Fields.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220407160621_Change_Precision_Training_Fields.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainingDetailConfigurations.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/CreateTrainingViewModel.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/UpdateTrainingViewModel.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs
- src/UserAdmin/test/Smart.FA.Catalog.IntegrationTests/Repositories/TrainingRepository_Tests.cs
- src/UserAdmin/test/Smart.FA.Catalog.Tests.Common/TrainingFactory.cs
- src/UserAdmin/test/Smart.FA.Catalog.UnitTests/Training_Tests.cs
1. Create a new field in the training model for the practical modalities with:
- Testing
- Validation
- Migration
2. Revise Precision in validators and domain layer of the training fields
- min and max length of Title, Methodology, Goal, PracticalModalities
> Add practical modalities field to training

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
This PR brings confirmation upon delete a training.
https://user-images.githubusercontent.com/90202188/162249464-e099a0f7-a25f-4bba-862c-c4613c2553df.mp4
Internal ticket:
https://smartjira.atlassian.net/browse/CFA-293
> Add a confirmation dialog upon deleting a training

- Jenkinsfile
- docker-compose.yml
- jenkins-deploy.sh
- src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Staging.json
- src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.json
Add minio settings to the docker compose project for Develop deployment
> Add minio inject variables in Docker configurations

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Program.cs
Commit 8acaf7f introduced support for localization in the showcase project.
However, I missed to stage a using line in the Program.cs breaking the build.
This commit fixes that.
internal ticket:
https://smartjira.atlassian.net/browse/CFA-338
> Showcase: Fix build compilation

- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220414184440_Add_SocialNetwork_Enumeration_Table.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220414184440_Add_SocialNetwork_Enumeration_Table.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/SocialNetworkConfiguration.cs
https://smartjira.atlassian.net/browse/CFA-327
> Generate SocialNetwork enumeration table

- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220414183714_Add_Fixed_Length_On_Trainer_Language_And_Email.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220414183714_Add_Fixed_Length_On_Trainer_Language_And_Email.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainerConfiguration.cs
This commit makes maximum length on email and default language respectively 254 and 2 characters long.
https://smartjira.atlassian.net/browse/CFA-325
> TrainerConfiguration: add constraint length on email and language

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Shared/_Layout.cshtml
just simple change for footer links
> Change links and delete one in footer

- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/CreateTrainingCommandHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220502154220_Add_IsGivenBySmart_To_Training.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220502154220_Add_IsGivenBySmart_To_Training.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainingConfiguration.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/CreateTrainingViewModel.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/UpdateTrainingViewModel.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs
This PR introduces a new IsGivenBySmart field accessible only by super-user in the create and update of a training and includes:
- Validation (only a super user can set the flag)
- A migration for the new field
- Domain model change
https://smartjira.atlassian.net/browse/CFA-334
> Add smart field for super user

- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Read/TrainingQueries.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
The PR is a hotfix of error of the paging system, it fixes:
- The layout of the next/previous buttons
- The fetching of specific rows of trainings
> Small fix of paging component

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
Just some corrections and new localization keys : 
- Add localization key for adminPart
- Add localization key in admin/homepage
- Add localization keys in Admin/Profile page
> Corrections french wording in admin interface

- src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/Smart.FA.Catalog.AccountSimulator.csproj
- src/UserAdmin/src/Smart.FA.Catalog.Web/Smart.FA.Catalog.Web.csproj
Update to 1.0.20-alpha the NuGet package.
Changes :
* Add the  form attribute to the SmartForm to specify the HTTP
* Add the form attribute to the SmartButton to specify the form
> Update Smart Design NuGet package to its latest revision

- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
> UserAdmin: TrainingList: Move the "You don't have any trainings yet" message higher on the screen

- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
> Move submit button of training creation, edition pages and profile édition page inside the navbar

- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Services/DomainEventPublisher.cs
PR #130  fixes the resolution of Domain Events however there was another error under the hood while looping over the collection.
This commit fixes that.
> Fix an error introduced with #130

- src/Shared/Smart.FA.Catalog.Shared/Collections/PagedList.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetPagedTrainingListFromTrainerQueryHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsByCriteriaQuery.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Extensions/PagedListExtension.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainings/List/SuperUserTrainingList.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainings/List/SuperUserTrainingList.cshtml.cs
In previous PR, a change of the paging of trainings broke the paging of the super user but was left untested.
Here is a hotfix to make an unified system for the paged list.
> Standarize paging super user

- src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Options/SpecialAuthenticationOptions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.json
This PR simply add an option for allowing/forbidding fake headers for testing with/out nginx.
> Add special authentication options for using fake headers

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Program.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Smart.FA.Catalog.Showcase.Web.csproj
This PR adds the nuget package and option which fixes the issue with retro-compatibily in SQL server 2008 (#128) in the showcase project.
> Add SQL 2008 fix to showcase

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
- Add a new div in Admin training list to constrain it in width
- Spelling corrections
> Syntaxt correction and css improve

- src/UserAdmin/src/Smart.FA.Catalog.Application/Interceptors/LoggingPipelineBehavior.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/DeleteTrainingCommand.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainersFromTrainingQueryHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingFromIdQueryHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsFromTrainerQueryHandler.cs
Improves the way logging is done when unhandied exceptions happen.
Instead of logging the exception's message the actual exception is logged so we do have the exception full details.
Removed try-catches to delegate to the logging behavior to do that job.
> Log properly exceptions

- src/Shared/Smart.FA.Catalog.Shared/Domain/Enumerations/Training/TrainingStatusType.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Trainer/ITrainerService.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/CreateTrainingCommandHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Enumerations/TrainingStatusExtensions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Enumerations/VatExemptionClaimExtensions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Specifications/TrainingSpecifications.cs
- src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220513094607_Replace_Validated_By_Published_Training_Status.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220513094607_Replace_Validated_By_Published_Training_Status.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/TrainingListingViewModel.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/AdminTrainingCardViewComponent.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
- src/UserAdmin/test/Smart.FA.Catalog.UnitTests/Training_Tests.cs
[Small PR for the renaming of the training validated to published status (as stated for V1).](https://smartjira.atlassian.net/browse/CFA-400)
Also add status color in the listing.
> Rename Validated training' status to Published

- src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/SuperUserJsonConverter.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml.cs
This happened in https://github.com/smartcoop/smart-cfa/commit/c205e44d411798dbbf32eba4ae8117f9b3aed9e6 due to breaking changes
> Fix build compilation due to wrong merge

- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.Designer.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.resx
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml
- Add localizations keys
- Add new wording on TrainerDetails page
- Add new wording on TrainerList page
- Add new wording on TrainingList page
> Add wording in showcase

- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
https://smartjira.atlassian.net/browse/CFA-394
> Fix label of maximum length of presentation and goal fields on training creation and update page

- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetPagedTrainingListFromTrainerQueryHandler.cs
Order training by "last modified" date in training list page.
https://smartjira.atlassian.net/browse/CFA-420
> Order training list by last modified date

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml
- Add two buttons in AdminHomepage and localization keys
- Add  new wording in UserChart page
- Add new wording in admin homepage
> Add new wording in admin user chart and homepage page

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Mappers/TrainerMapper.cs
https://smartjira.atlassian.net/browse/CFA-421
Fix lower case for icone name
> Fix path for social network icon on trainer details page

- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.Designer.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.resx
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml
There will be a message stating no trainers were found after a search
> Showcase: display a message when no trainers were found

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Handlers/UserAdminAuthorizationResultHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Options/UrlOptions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/SideMenuItems.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Index.cshtml.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Routes.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_Layout.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.PreProduction.json
- src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Production.json
- src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Staging.json
- src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.json
In production the redirection on cfa will add a /cfa base path this add the necessary things to make the site works.
> Add a 'cfa' base path to user admin URL so the website works with nginx

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Shared/_Layout.cshtml
> Correct links for favicons

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
> Correct 2 syntax errors

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/SideMenuItems.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs
This PR:
1. Sets all routes to lower-case
2. Change wording "Se connecter" to "Déconnexion" to be coherent with Account
> Change wording for Signing out and Routing in lowercase

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Shared/_Layout.cshtml
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Trainer/TrainerService.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Routes.cs
> Change showcase accès membre redirection

- src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingList.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/CatalogShowcaseContext.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainingList.sql
- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.Designer.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.resx
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Training/ITrainingService.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Training/TrainingService.cs
Add search bar
Add Topic filters
https://smartjira.atlassian.net/browse/CFA-270
> Showcase > Add search in training page

- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainerList.sql
- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainingDetails.sql
- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainingList.sql
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220518184922_Set_DateTime_To_3_Precision.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/20220518184922_Set_DateTime_To_3_Precision.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/EntityConfigurations/EntityConfigurationBase.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/UserChartRevisionConfiguration.cs
* Set datetime2 precision to 3 (requested by @JOABAUDENS )
* Update v_TrainerList to look on enumeration TrainingStatusType's name instead of id (idem )
see https://github.com/smartcoop/smart-back-end/pull/2530
> Update SQL to match ssdt

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Extensions/HtmlExtensions.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Extensions/StringExtensions.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
PR introducing the conservation of line breaks in the descriptions fields of Trainings and Trainers in the showcase project.
> Conserve line breaks in training and trainer description

- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsByCriteriaQuery.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/AdminTrainingCardViewComponent.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainings/List/SuperUserTrainingList.cshtml
Now super users can filter when searching by a trainer's name.
https://smartjira.atlassian.net/browse/CFA-426
> UserAdmin: SuperUserTrainingList: add support for searching trainings by training creator name

- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/EditProfileCommand.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UploadTrainerProfileImageCommand.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/MinIoLinkGenerator.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs
This PR refactor the profile picture form part of the profile page to:
- Separate the call from the rest of the form
- Generate an unique hash at each upload to avoid browser caching
> Rewrite minio handler

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Training/ITrainingService.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Training/TrainingService.cs
Add missing filter to only display published trainings in training list paging.
> Filter out unpublished trainings

- src/Shared/Smart.FA.Catalog.Shared/Domain/Enumerations/Trainer/SocialNetwork.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.Designer.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.resx
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
Simply add translation to the key word "Personal website".
before
now
> Localize string "Personal website"

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainings/List/SuperUserTrainingList.cshtml
- Correct localization key
- Improve the display of Superuser page
> Improve display superuser page

- src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.resx
> Correct localization keys

- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml.cs
Add info messege when draft training
https://smartjira.atlassian.net/browse/CFA-427
> Add info messege when draft training

- src/Showcase/test/Smart.FA.Catalog.Showcase.Infrastructure.Tests/Mailing/TemplateEmailServiceTests.cs
Due to a suggestion apply in PR to send a mail to a trainer, the build was broken
> Fix showcase test compilation

- README.md
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Properties/launchSettings.json
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/README.md
Add readme file for Showcase Web project
https://smartjira.atlassian.net/browse/CFA-306
> Add readme file for Showcase Web project

- src/UserAdmin/src/Smart.FA.Catalog.Core/Extensions/TypeExtensions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/CatalogContext.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainerSocialNetworkConfiguration.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainingAttendanceConfiguration.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainingConfiguration.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainingTargetAudienceConfigurations.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainingTopicConfiguration.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/VatexemptionClaimConfiguration.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/EfCore/Converters/EnumerationConverter.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/EfCore/Extensions/ModelBuilderExtensions.cs
- src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/EfCore/Extensions/TypeExtensions.cs
- src/UserAdmin/test/Smart.FA.Catalog.UnitTests/Extensions/TypeExtensionsTest.cs
- src/UserAdmin/test/Smart.FA.Catalog.UnitTests/Infrastructure/EfCore/EnumerationConverterTests.cs
- src/UserAdmin/test/Smart.FA.Catalog.UnitTests/Smart.FA.Catalog.UnitTests.csproj
Introduces an extension method on ModelBuilder to apply conversion on enumeration
between their type and their value.
> Add Ef Core automatic conversion on Enumerations

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml.cs
https://smartjira.atlassian.net/browse/CFA-479
BEFORE
AFTER
> Showcase: list of trainers: display eight tiles instead of five

- src/Shared/Smart.FA.Catalog.Shared/Helper/UriHelper.cs
- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/EditProfileCommand.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
- src/UserAdmin/test/Smart.FA.Catalog.UnitTests/Helpers/UriHelperTests.cs
It is not longer possible to enter wrong url when a trainer edits its profile
https://smartjira.atlassian.net/browse/CFA-478
> Trainer profile: add validation on social network urls

- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/PaginationExtensions.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainerQueryableExtensions.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
https://learning.smart.coop/Training/TrainingList/TrainingList and
https://learning.smart.coop/Trainer/TrainerList/TrainerList
are randomized with this PR.
> Applies randomization on showcase trainer and training list pages

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml.cs
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
fixes https://smartjira.atlassian.net/browse/CFA-505
> Showcase: preserve search keyword on the resulting page

- src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/AccountDataHeaderHeaderSerializer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/IAccountDataHeaderSerializer.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/Validators/AccountHeadersValidator.cs
- src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/Validators/CustomDataFieldsValidator.cs
While reviewing #241 I noticed a bunch of typos I made formerly.
@Victor-van-Duijnen 
YOu just have a super easy conflict to handle.
This can be merged in main & your ongoing branch sync
> UserAdmin: Authentication: fix a bunch of typos and move validators in a separate folder

- src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainersByCriteraExceptSelfQuery.cs
> Remove unnecessary includes

- src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Migrations/20220711104431_empty.Designer.cs
> [ShowCase] Fix migration

- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/appsettings.Production.json
- src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Production.json
Change of the connectring string database (public website and administrator) for targeting the new sql server in production.
> Change prod sql server cn name

- docker-compose.yml
- pipeline-scripts/jenkins-deploy.sh
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Smart.FA.Catalog.Showcase.Web.csproj
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/appsettings.Staging.json
- src/Showcase/src/Smart.FA.Catalog.Showcase.Web/appsettings.json
This PR improves the jenkins pipeline scripts by adding a static instance of minio (remove per-instance minio-server) and adding showcase for dev' deployment.
It also add comments in the Jenkins file so that other developer can jump in more easily.
> Add showcase to jenkins pipeline

- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
Serializing huge modelstate in tempdata can create huge cookies that would span 431 http request
> Replace redirect while preserving modelstate with simple page return

- src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Shared/_TrainingCreationEditionForm.cshtml
Create custom rich text editor while removing link metadata in text.
> Custom define rich text editor formatting
