smartcoop/smart-cfa

src/Smart.FA.Catalog.Web/Program.cs
src/Smart.FA.Catalog.Web/Properties/launchSettings.json
src/Smart.FA.Catalog.Web/appsettings.Development.json

The application fails to build from a fresh clone. This is due to the fact the appsettings.Local.json is mandatory and not integrated in the repository.
Conceptually the appsettings.Local.json should be optional and give the possiblity to override appsettings.Development.json's default settings.
Default connection string for Catalog has been set to "(LocalDB)\\MSSQLLocalDB; Database=Catalog; Integrated Security=true;".

AppSettings: revert default environment from Local to Development

---

src/Smart.FA.Catalog.Core/Domain/Models/CustomIdentity.cs
src/Smart.FA.Catalog.Core/Services/IUserIdentity.cs
src/Smart.FA.Catalog.Web/Extensions/Middlewares/ProxyHeaderMiddleware.cs
src/Smart.FA.Catalog.Web/Identity/UserIdentity.cs
src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml.cs
src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml.cs
src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml.cs
src/Smart.FA.Catalog.Web/Pages/Index.cshtml.cs

This commit introduce a service that can be used across all layers.
Currently the Identity is strongly typed inside the HttpContext. 
Therefore only the Web layer can retrieve current user identity.
By adding a service that provides the identity through DI we can retrieve the identity at the infrastructure or application layer.

Add a service to retrieve identity of current user

---

src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml

Currently the _AdminLayout.cshtml is not up to date with the Design System's one.
A correct implementation can be seen here: https://design.smart.coop/development/trainings/administrative-profile.html.
--
This commit updates the admin layout accordingly to this one:  ttps://design.smart.coop/development/trainings/administrative-profile.html.
The following changes were also made:
* remove unnecessary items in the application's toolbar, i.e, management, Documents, etc anchors.
* the section `HeaderToolbar` doesn't expect a navbar element but a toolbar or anything else.

Update the _AdminLayout.cshtml file to match the Smart Design System one

---

src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
src/Smart.FA.Catalog.Web/wwwroot/js/lib.js

When the validation fails, we want to have the first element to be scrolled to and focused.
The reason is that if the failures is deep at the bottom of a page it is not user friendly to understand there was an error.

Refactor the javascript that scroll and focus to the first HTML element in an error state

---

src/Smart.FA.Catalog.Application/UseCases/Commands/CreateTrainerFromUserAppCommandHandler.cs
src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainerFromUserAppQueryHandler.cs
src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
src/Smart.FA.Catalog.Core/Exceptions/Error.cs
src/Smart.FA.Catalog.Core/Exceptions/UserException.cs
src/Smart.FA.Catalog.Web/Extensions/Middlewares/ProxyHeaderMiddleware.cs

Separate fetching an user and its potential linked trainer from the user id and from creating the trainer if no trainer is linked to an userId/applicationtypeid in order to have a good command/query division (queries should not update data)

Divide proxy header middleware in multiple commands/queries

---

src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml.cs

When a post failure happens we need to call the method that initializes the page.
That is why the side menu was no longer selected correctly.

Fix side menu not selected upon training edition failure

---

src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingFromIdQueryHandler.cs
src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml.cs
src/Smart.FA.Catalog.Web/Program.cs

Putting an ID that does not exist in the browser would result in an internal error: null reference exception.

Prevent a internal error when accessing the edition of a non-existent training

---

src/Smart.FA.Catalog.Infrastructure/Persistence/Write/TrainingRepository.cs
src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/UpdateTrainingViewModel.cs

Because the topics were not correctly loaded, they were never cleared correctly during the save.
This resulted into a duplication primary sql error.
Making them tracked corrects the problem.
Also made sure to include the topic's ids in the view model of the page otherwise the existing topic are not checked.

Prevent internal error when editing a training

---

src/Smart.FA.Catalog.Application/Extensions/FluentValidation/OnStringRuleBuilderExtensions.cs
src/Smart.FA.Catalog.Application/UseCases/Commands/EditProfileCommand.cs
src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainerProfileQuery.cs
src/Smart.FA.Catalog.Core/Domain/Trainer/Trainer.cs
src/Smart.FA.Catalog.Core/Helpers/EmailValidator.cs
src/Smart.FA.Catalog.Core/SeedWork/Guard.cs
src/Smart.FA.Catalog.Infrastructure/Migrations/20220325153842_Add_Email_To_Trainer.Designer.cs
src/Smart.FA.Catalog.Infrastructure/Migrations/20220325153842_Add_Email_To_Trainer.cs
src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
src/Smart.FA.Catalog.Localization/CatalogResources.resx
src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs

This commit introduces the possibility for users to specify their email.
* A new guard clause is added to validate emails.
* A new rule builder extension on string to validate email has been added.
* Imported [EmailValidator](https://github.com/jstedfast/EmailValidation/blob/master/EmailValidation/EmailValidator.cs) class, this make us independent of the NuGet.
* The library passes the following  [tests](https://github.com/jstedfast/EmailValidation/blob/master/UnitTests/EmailValidationTests.cs)

Add support to the user profile page to specify an email

---

src/Smart.FA.Catalog.Application/Interceptors/LoggingPipelineBehavior.cs
src/Smart.FA.Catalog.Application/Models/Options/MediatROptions.cs
src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
src/Smart.FA.Catalog.Web/Options/AdminOptions.cs
src/Smart.FA.Catalog.Web/Program.cs
src/Smart.FA.Catalog.Web/appsettings.Development.json
src/Smart.FA.Catalog.Web/appsettings.json

This commit introduces a new application settings `LogRequests`.
When this settings is equal to true, the commands and queries are logged.
This setting is by default equal to false but on development build.
--------------
@Victor-van-Duijnen 
Something else I changed:
Note an IConfiguration object is sent to the AddApi extensions in place of an IConfigurationSection over the time the applcation settings will grow and ending with 3,4,5,6 + sections will eventually occur, I think it is better to pass direct one single object.

Add logging of commands and queries on development builds

---

src/Smart.FA.Catalog.Core/LogEvents/GeneralLogEvents.cs
src/Smart.FA.Catalog.Core/SeedWork/DomainEvent.cs
src/Smart.FA.Catalog.Core/SeedWork/Entity.cs
src/Smart.FA.Catalog.Core/SeedWork/IDomainEventPublisher.cs
src/Smart.FA.Catalog.Infrastructure/Extensions/ServiceCollectionExtensions.cs
src/Smart.FA.Catalog.Infrastructure/Persistence/CatalogContext.cs
src/Smart.FA.Catalog.Infrastructure/Services/DomainEventPublisher.cs

MediatR has its own memory bus and makes it easy in an elegant way to create code that handles event publishing.
The event publishing happens now after the database transaction. This avoids scenarios such mail being sent upon the creation of something but the database transaction actually failed.
However, in a future we would like to have the handling happening within the database transaction.
This PR introduces:
- A new type and interface for domain events
- Uses MediatR for the actual event publishing
- Update MediatR library to latest version (10.0)

Use MediatR to handle publishing of domain events

---

src/UserAdmin/src/Smart.FA.Catalog.Application/Interceptors/LoggingPipelineBehavior.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Development.json

The LoggingPipelineBehavior class logs in development environments requests that come in.
If the request has circular references, example, an entity, such Trainer, it will result with into an exception because it produces an infinite loop.
Internal Jira ticket: https://smartjira.atlassian.net/browse/CFA-290
Some doc: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-preserve-references?pivots=dotnet-6-0

MediatR: when serializing requests prevent circular errors

---

src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Dto/TrainingDto.cs
src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Read/TrainingQueries.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/AdminTrainingCardViewComponent.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml

The Introduction of topic ids (also called categories or tags) had broken the paging system of the list of trainings.
The PR maps topic ids to a list in Training dto with the multi-mapping feature of dapper to fix the paging.

Fix broken paging in training listing page

---

src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js

There was  a onload event logic applied globally to every pages but that logic is related only to creation and edition pages.
Therefore opening any pages but those two would result in this:
'Cannot read properties of null (reading 'addEventListener')'.
This PR provides a quick and dirty fix by returning in nothing is found.
Internal ticket:
https://smartjira.atlassian.net/browse/CFA-322

Fix JS error on loading of most pages

---

src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Development.json

S3Storage and AWS sections are nested into AdminOptions instead of being at the root.
This commit fixes that.

Fix resolving S3 settings on development builds

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Smart.FA.Catalog.Web.csproj

Updating to 1.0.19-alpha fixes main.css.map not being found.

NuGet: update Smart.Design.Razor to its latest revision

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml

<link rel="stylesheet" href="@(nameof(Smart.FA.Catalog.Web)).styles.css" /> is wrong synthax therefore
the  proxy middleware is being flooded due to the 404 response that redirects to the no found page.

Fix 404 http calls due to wrong <link> reference in HTML head tag

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs

A hotfix to remove forced Preproduction appsettings (useless, by default the app will take the appsettings based on the ASPNETCORE_ENVIRONMENT)

Remove forced Preproduction appsettings

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js

Just disable submitting the form when pressing enter on the create and edit page of trainings.
Hitting ENTER submit as a draft but we don't want necessarily to have that behavior.

Disable event on key enter pressed on form in training creation and edition pages

---

src/UserAdmin/src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs

GitHub social network doesn't exist nor the personal website in our icons.
Therefore there was a try catch surrounding the image enum parsing in case of failure.
Doing so raises error in debug mode on breaking on exception throwned.
this behavior is a bit annoying so this commit prevent exception being thrown.

ProfileViewModels: socialNetwork mapping: don't encapsulate parsing in a try-catch but check if name exists

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs

Translation was missing when the training field is empty.

CreateTrainingRequestValidator: add missing translation for training title validation

---

src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/SetTrainerHasAcceptedLatestUserChartRevisionCommand.cs
src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Trainer/Trainer.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml.cs

Approving an already approved user chart revision leads to a duplication of primary key of the many to many table between userchart revisions and trainers.
Fixed that behavior by loading correctly the current trainer's user chart approvals and also redirect to the home page users that are either super user or having approved a active user chart revision.

Prevent invalid operation when approving an already approved user chart revision

---

src/UserAdmin/src/Smart.FA.Catalog.Application/Interceptors/LoggingPipelineBehavior.cs
src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/SuperUserJsonConverter.cs
src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/TrainerAssignmentJsonConverter.cs
src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/TrainerJsonConverter.cs
src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/TrainingJsonConverter.cs
src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/UserChartRevisionJsonConverter.cs

Due to circular references between properties of entities like Trainer and Training (they are aggregate/entities after all) serialization 
produces very large JSON because of the lazy loading enable in EF Core.
Serializing an object make the serializer accessing every public properties; this trigger lazy evaluation of each unloaded ones which can result in unnecessary and heavy SQL statements.
Commit 9188b484c36031536ac373fbd0691b381962e23a serializes request that results in an exception, I was to avoid the issues described above.
This commit adds five JsonConverters on entities that are sent between web and BL to convert them to their primary key value rather the whole object value.
This should be considered as a dirty fix and DTOs should be considered over entities; or domain models …

LoggingPipelineBehavior: don't log Trainer nor Training domain models that transit through MediatR

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs

Currently the page is re-rendered  to display a successful message, however doing so won't reload the newly uploaded image (if any).
This commit ensures that the page reloads itself and therefore refresh the trainer's profile image.
https://smartjira.atlassian.net/browse/CFA-422

Reload edit profile page after a successful edition

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml

Due to the HTML update of the list page the changes need to be reflected on the global banner also.
becomes

Surround global banner on training listing page with a o-container

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_Layout.cshtml

HTML was ajusted from https://design.smart.coop/prototypes/account/user-homepage-with-menu.html.

Update HTML of usermenu to match account

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Options/UrlOptions.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Index.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.PreProduction.json
src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Production.json
src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.json

The production URL of the Showcase website was hardcoded. It can now be set through an option.

Make URL of Showcase website customizable accordingly to underlying environment

---

src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/EditProfileCommand.cs

in order to make 
```html
<a> 
```
HTML tags work the uri must have a http or https protocol set in the url.
example: 
```html
<a href="www.smart.coop"  /> 
```
won't point to http://www.smart.coop 
This commit ensures that https protool is prepended when a trainer saves its profile.

Prepend https protocol on social network urls

---

src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/CreateTrainingViewModel.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Shared/_TrainingCreationEditionForm.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/UpdateTrainingViewModel.cs
src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs

Simply move the HTML of the form to create or edit a training into a partial view.
This will help maintaining those two pages.
If somebody got a better naming for
[_TrainingCreationEditionForm.cshtml](https://github.com/smartcoop/smart-cfa/pull/239/files#diff-b43f5e5d2115aab83f76fa130af49942db3ac6369055dd9d1618a200557c3554) say so :).
This PR is required for https://smartjira.atlassian.net/browse/CFA-432

Extract training creation/edition form into a partial view

---

src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Smart.FA.Catalog.Showcase.Web.csproj
src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Extensions/ServiceCollectionExtensions.cs
src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Smart.FA.Catalog.Infrastructure.csproj

This PR removes the use of a nuget package allowing ef core to translate skip and take with ef core in old SQL language (ROW NUMBER) supported on SQL 2005. With the migration in production to a newer version of SQL, it is not needed anymore.

Remove old system for paging (with sql server update)
